sudo: required

services:
  - docker

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t jabaridash/weather-api .
  - |
    docker run                                         \
    -d                                                 \
    -p 8080:80                                         \
    --env OPEN_WEATHER_API_KEY="$OPEN_WEATHER_API_KEY" \
    --env IOS_APP_ID="$IOS_APP_ID"                     \
    --env ANDROID_APP_ID="$ANDROID_APP_ID"             \
    --name weather-api                                 \
    jabaridash/weather-api
  - sleep 15
  - docker ps -a
  - npm test
  - docker push jabaridash/weather-api

on:
  branch: master
